### ISSUE TITLE
Servo Calibration Functionality

### ISSUE THREAD

**Issue by michaelshiel** [CartesianCo/argentum-control#10]

**Comment by dunaden001** [comment]
As further explanation on what challenges are involved here:
- When assembling the printer, it is ideal that the user does not have to place the servo horn perfectly as this is quite difficult.  As a result, each printer will have a different value for equivalent physical angles of the deployed roller. This will also account for inconsistencies in servo manufacture.
- If a servo is driven to a point that it is limited from physically reaching, it will eventually burn out the motor.  As the initial relationship between commanded angle and physical roller angle are not initially known, this means care must be taken on intial set-up to not drive the servo too far for long periods.

My suggestion for circumventing this is to have a calibration system that lets you set the retracted angle and click a test button.  This will engage the servo into position for say ~500ms which will prevent burning out even if it is incorrect.  The user tries new values until the motor can reach the set angle without straining and then calibration for the retracted angle is complete.

A similar method can then be used to set the deployed angle.  It would be ideal if a set of deployed angles could be set so that one could have a separate value for FR4 (1.5mm thick) and paper (~0.5mm thick?).

**Comment by trent-waddington** [comment]
When you get to China and are all settled in, take a look at Terry Mackintosh's commits for servo calibration and add any comments here that you think are relevant.
