### ISSUE TITLE
Printing is not intuitive and repeatable

### ISSUE THREAD

**Issue by trent-waddington** [CartesianCo/argentum-control#28]
Currently, the software does not have a sensible concept of a "print start position", with the user responsible for manually jogging the print head to a sensible start position and then hoping that the print occurs at the designed position in the print area. This results in poor repeatability as often the print head has to be moved out of the way for drying in multi-pass prints. The print head moves right to left, this is mainly an artifact of manual jogging (you want to be able to see where you will print) but is not intuitive to most users.

The best solution would provide a graphical placement tool for the user to orient print surfaces inside the print area. There are white "plus marks" inside the print area which can be used to provide a visual cue that could be combined with visualization of available processed images.

**Comment by dhylands** [comment]
I would also love to see a "Return to Start-of-Print Position" button. The printer knows where this is because it returns the print head there when it finishes printing a layer.

Having the head automatically move to an area away from the print area (rather than the start of print position) at the end of a print would be useful as well.

Thinking about it some more, perhaps having a "print from current position" and "print from start position" commands/buttons makes more sense. Then you could do:

1 - Print from current position. The printer prints a layer, moves to the "away" position.
2 - You blot your board
3 - Reprint - the head moves back to the start of the previous print, prints a layer, and moves to the "away" position.
4 - Goto 2

**Comment by dunaden001** [comment]
I believe that the best way to handle this is similar to the standard that 3D printers currently use.  The work flow would be:

1 - user assigns a print bed position to the layer before 'slicing'.  This can be done in the GUI by dragging and placing the image in the print bed (as described by Trent above).  In the interim, this could be done by just inputting an offset for x and y in a pair of simple text entry widgets.
2 - user has the option for adding custom commands to the layer after it is finished (such as home X positive, home X negative, home Y positive, home both XY positive etc.)
3 - user puts code on SD card and hits print.  The printer first homes to x=0, y=0 and then the first pair of commands are always to move to the start position of the print.  Given that the printer has just homed, this will work even if the printer has just been turned on or reset.  This will also resolve any issues with soft stops occurring on start up as the printer will always know it's absolute position before beginning a layer.
4 - Carriage finishes layer and then performs custom added command (eg. home X positive).
5 - User dries, or does whatever they need to
6 - Repeat from 3

NOTE: the only reason that this method may not be ideal is that the positional repeatability of the home limit switches is not as accurate as the repeatability in the stepper motors.

**Comment by trent-waddington** [comment]
Resolved by Print View.
