### ISSUE TITLE
Ability to enable/disable stepper motors

### ISSUE THREAD

**Issue by michaelshiel** [CartesianCo/argentum-control#3]

**Comment by dunaden001** [comment]
It would be useful to have a set command for this so that it could also be included as a custom post layer command.  If the workflow is changed to home the carriage before each layer as in #28, it would be ideal for power consumption, noise, heat generation and ease of movement to disable the motors after a layer.

**Comment by trent-waddington** [comment]
I have no idea what this ticket is about.

**Comment by mkohler99** [comment]
I think this is useful for doing mechanical work on the printer. If the steppers are disabled it would be possible to move the carriage by hand. Also, when the steppers are disabled the machine draws less power and makes less heat. This would be a good thing for the "STOP" button if it is to function as an E Stop, because if you got something caught in the machine you could stop it and more easily clear the jam.

**Comment by trent-waddington** [comment]
So, like, what's wrong with the power switch?

**Comment by trent-waddington** [comment]
I added a motors on/off button on the console.

**Comment by trent-waddington** [comment]
I also made sure the motor comes on when a print is started.

**Comment by trent-waddington** [comment]
I added a preference to start with motors turned off. (defaults to off.)
